"use client";
import { useState } from "react";
import Link from "next/link";

export default function CartPage() {
  const [cartItems, setCartItems] = useState([
      { id: 1, name: "دورة تطوير المواقع الشاملة", category: "برمجة", price: 299, image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=200" },
          { id: 2, name: "أساسيات الذكاء الاصطناعي", category: "تقنية", price: 199, image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=200" },
            ]);
              const [promoCode, setPromoCode] = useState("");

                const removeItem = (id: number) => setCartItems(cartItems.filter((item) => item.id !== id));

                  const subtotal = cartItems.reduce((sum, item) => sum + item.price, 0);
                    const tax = Math.round(subtotal * 0.15);
                      const total = subtotal + tax;
                        const isEmpty = cartItems.length === 0;

                          return (
                              <div className="bg-[#f8fafc] font-[Cairo] text-[#1A2A3A] min-h-screen" dir="rtl">
                                    <div className="max-w-[1200px] mx-auto py-10 px-5">
                                            <h1 className="font-black text-2xl md:text-3xl mb-8 flex items-center gap-3"><i className="fas fa-shopping-basket text-[#00B4D8]" /> سلة المشتريات</h1>
                                                    {!isEmpty ? (
                                                              <div className="grid grid-cols-1 lg:grid-cols-[1fr_380px] gap-8 items-start">
                                                                          <div className="flex flex-col gap-4">
                                                                                        {cartItems.map((item) => (
                                                                                                        <div key={item.id} className="bg-white rounded-[20px] p-5 border border-[#e2e8f0] flex items-center gap-5 hover:-translate-y-1 hover:shadow-md transition max-sm:flex-col max-sm:text-center">
                                                                                                                          <img src={item.image} alt={item.name} className="w-[100px] h-[70px] rounded-xl object-cover" />
                                                                                                                                            <div className="flex-1"><h3 className="font-bold text-lg mb-1">{item.name}</h3><span className="text-sm text-[#00B4D8] font-bold">{item.category}</span></div>
                                                                                                                                                              <div className="flex flex-col items-end gap-2.5 max-sm:items-center max-sm:w-full max-sm:border-t max-sm:border-gray-100 max-sm:pt-4">
                                                                                                                                                                                  <p className="font-extrabold text-xl text-[#1A2A3A]"><span className="text-xs text-[#64748b] mr-1">ريال</span>{item.price}</p>
                                                                                                                                                                                                      <button onClick={() => removeItem(item.id)} className="bg-red-50 text-red-500 border-none py-2 px-3 rounded-[10px] cursor-pointer font-bold text-sm hover:bg-red-100 transition"><i className="fas fa-trash-alt ml-1" /> حذف</button>
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                              <div className="bg-white rounded-[25px] p-8 border border-[#e2e8f0] sticky top-[100px]">
                                                                                                                                                                                                                                                                                            <h2 className="font-extrabold text-xl mb-6 border-b border-gray-100 pb-4">ملخص الطلب</h2>
                                                                                                                                                                                                                                                                                                          <div className="flex gap-2.5 mb-6 bg-[#f8fafc] p-2 rounded-[15px]">
                                                                                                                                                                                                                                                                                                                          <input type="text" placeholder="كود الخصم" value={promoCode} onChange={(e) => setPromoCode(e.target.value)} className="flex-1 bg-transparent border-none py-2.5 px-2 font-[Cairo] text-sm outline-none" />
                                                                                                                                                                                                                                                                                                                                          <button className="bg-[#1A2A3A] text-white border-none px-5 rounded-[10px] font-bold cursor-pointer text-sm">تطبيق</button>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between mb-4 text-[#64748b] font-semibold"><span>المجموع الفرعي</span><span>{subtotal} ريال</span></div>
                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex justify-between mb-4 text-[#64748b] font-semibold"><span>الضريبة (15%)</span><span>{tax} ريال</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-between mt-5 pt-5 border-t-2 border-dashed border-gray-100 text-[#1A2A3A] text-2xl font-black"><span>الإجمالي</span><span>{total} ريال</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                <button className="w-full bg-[#10b981] text-white border-none py-[18px] rounded-[18px] font-[Cairo] font-extrabold text-lg cursor-pointer flex items-center justify-center gap-2.5 mt-6 hover:scale-[1.02] hover:shadow-lg transition shadow-md">إتمام الطلب والدفع <i className="fas fa-chevron-left" /></button>
                                                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/" className="block text-center mt-5 text-[#64748b] font-bold text-sm hover:text-[#00B4D8] transition">متابعة التسوق</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-center py-20 px-5 bg-white rounded-[30px] border border-[#e2e8f0]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <i className="fas fa-cart-plus text-6xl text-[#e2e8f0] mb-5 block" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="font-extrabold text-xl mb-2.5">سلتك فارغة حالياً</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-[#64748b] mb-8">لم تضف أي دورات إلى سلتك بعد</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link href="/" className="inline-flex bg-[#00B4D8] text-white py-4 px-10 rounded-[15px] font-extrabold">تصفح الدورات المتاحة</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }