'use client';

import { useCartStore } from '@/lib/cart-store';

interface Course {
  id: number;
    title: string;
      category: string;
        price: number;
          image: string;
            instructor: string;
              description: string;
                lessons: number;
                  duration: number;
                    learningOutcomes: string[];
                      requirements: string[];
                      }

                      export default function CourseClient({ course }: { course: Course }) {
                        const addItem = useCartStore((state) => state.addItem);

                          return (
                              <div className="course-page-wrapper">
                                    <div className="back-nav">
                                            <a href="/" className="btn-back">
                                                      <i className="fas fa-arrow-right"></i> العودة للمتجر
                                                              </a>
                                                                    </div>

                                                                          <div className="course-layout">
                                                                                  <main className="course-main-content">
                                                                                            <span className="course-category">{course.category}</span>
                                                                                                      <h1 className="course-title">{course.title}</h1>

                                                                                                                <div className="instructor-info">
                                                                                                                            <i className="fas fa-chalkboard-teacher"></i>
                                                                                                                                        <span className="instructor-name">يقدمها: {course.instructor}</span>
                                                                                                                                                  </div>

                                                                                                                                                            <div className="section-box">
                                                                                                                                                                        <h2 className="section-title">
                                                                                                                                                                                      <i className="fas fa-align-right"></i> وصف الدورة
                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                              <p>{course.description}</p>
                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                  <div className="section-box">
                                                                                                                                                                                                                                              <h2 className="section-title">
                                                                                                                                                                                                                                                            <i className="fas fa-graduation-cap"></i> ماذا ستتعلم في هذه الدورة؟
                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                    <ul className="list-items">
                                                                                                                                                                                                                                                                                                  {course.learningOutcomes.map((item, index) => (
                                                                                                                                                                                                                                                                                                                  <li key={index}>
                                                                                                                                                                                                                                                                                                                                    <i className="fas fa-check-circle"></i>
                                                                                                                                                                                                                                                                                                                                                      <span>{item}</span>
                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="section-box">
                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="section-title">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <i className="fas fa-list-check"></i> متطلبات الدورة
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ul className="list-items">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {course.requirements.map((item, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li key={index}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <i className="fas fa-check-circle"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>{item}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <aside className="course-sidebar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <img src={course.image} alt={course.title} className="course-cover" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="sidebar-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="price-box">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="current-price">{course.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="currency">ريال سعودي</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="course-stats">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="stat-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <i className="fas fa-tag"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="stat-val">{course.category}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="stat-label">التصنيف</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="stat-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <i className="fas fa-layer-group"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="stat-val">{course.lessons} درس</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="stat-label">محتوى</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="stat-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <i className="fas fa-clock"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="stat-val">{course.duration} يوم</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="stat-label">اشتراك</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="btn-add-to-cart"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => addItem(course.id, course.title, course.price)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <i className="fas fa-shopping-cart"></i> إضافة إلى السلة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ textAlign: 'center', fontSize: '0.8rem', color: '#94a3b8', marginTop: '15px', fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i className="fas fa-shield-halved"></i> وصول آمن وفوري للمحتوى
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }