"use client";

import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";

export default function HeaderClient() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
    const [hideHeader, setHideHeader] = useState(false);
      const pathname = usePathname();
        const lastScrollY = useRef(0);
          const stickyRef = useRef<HTMLDivElement>(null);
            const spacerRef = useRef<HTMLDivElement>(null);

              const mode = pathname === "/upload-course" ? "teacher" : "student";

                useEffect(() => {
                    const handleScroll = () => {
                          const currentScrollY = window.scrollY;
                                if (currentScrollY > lastScrollY.current && currentScrollY > 100) {
                                        setHideHeader(true);
                                              } else {
                                                      setHideHeader(false);
                                                            }
                                                                  lastScrollY.current = currentScrollY <= 0 ? 0 : currentScrollY;
                                                                      };
                                                                          window.addEventListener("scroll", handleScroll, { passive: true });
                                                                              return () => window.removeEventListener("scroll", handleScroll);
                                                                                }, []);

                                                                                  useEffect(() => {
                                                                                      const syncHeight = () => {
                                                                                            if (stickyRef.current && spacerRef.current) {
                                                                                                    spacerRef.current.style.height = stickyRef.current.offsetHeight + "px";
                                                                                                          }
                                                                                                              };
                                                                                                                  syncHeight();
                                                                                                                      const observer = new ResizeObserver(syncHeight);
                                                                                                                          if (stickyRef.current) observer.observe(stickyRef.current);
                                                                                                                              window.addEventListener("resize", syncHeight);
                                                                                                                                  setTimeout(syncHeight, 100);
                                                                                                                                      setTimeout(syncHeight, 500);
                                                                                                                                          return () => {
                                                                                                                                                observer.disconnect();
                                                                                                                                                      window.removeEventListener("resize", syncHeight);
                                                                                                                                                          };
                                                                                                                                                            }, []);

                                                                                                                                                              const toggleSidebar = () => setSidebarOpen(!sidebarOpen);

                                                                                                                                                                return (
                                                                                                                                                                    <>
                                                                                                                                                                          <div
                                                                                                                                                                                  className={`fixed inset-0 bg-black/30 backdrop-blur-sm z-[2000] transition-opacity duration-300 ${
                                                                                                                                                                                            sidebarOpen ? "opacity-100 visible" : "opacity-0 invisible"
                                                                                                                                                                                                    }`}
                                                                                                                                                                                                            onClick={toggleSidebar}
                                                                                                                                                                                                                  />

                                                                                                                                                                                                                        <aside
                                                                                                                                                                                                                                className={`fixed top-0 right-[-350px] w-[320px] h-full bg-white z-[2100] transition-all overflow-y-auto p-10 ${
                                                                                                                                                                                                                                          sidebarOpen ? "right-0" : ""
                                                                                                                                                                                                                                                  }`}
                                                                                                                                                                                                                                                          style={{ transitionDuration: "0.4s" }}
                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                        <div className="flex justify-between items-center mb-8">
                                                                                                                                                                                                                                                                                  <img
                                                                                                                                                                                                                                                                                              src="http://a.theorix.net/wp-content/uploads/2026/04/file_0000000083d4720abfa704bf8b172784.png"
                                                                                                                                                                                                                                                                                                          alt="شعار"
                                                                                                                                                                                                                                                                                                                      className="h-[42px] w-auto max-w-[150px] object-contain"
                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                          <button onClick={toggleSidebar} className="text-[45px] text-red-500 leading-none cursor-pointer bg-transparent border-none">×</button>
                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                          <nav className="flex flex-col">
                                                                                                                                                                                                                                                                                                                                                                    <Link href="/" onClick={toggleSidebar} className="flex items-center gap-3 p-4 text-[#0A3A6B] font-bold rounded-xl hover:bg-gray-100 hover:text-[#07A4A2] transition">
                                                                                                                                                                                                                                                                                                                                                                                <i className="fas fa-home" /> الرئيسية
                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/cart" onClick={toggleSidebar} className="flex items-center gap-3 p-4 text-[#0A3A6B] font-bold rounded-xl hover:bg-gray-100 hover:text-[#07A4A2] transition">
                                                                                                                                                                                                                                                                                                                                                                                                                <i className="fas fa-wallet" /> بطاقاتي الدراسية
                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <hr className="border-t border-gray-200 my-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/about" onClick={toggleSidebar} className="flex items-center gap-3 p-4 text-[#0A3A6B] font-bold rounded-xl hover:bg-gray-100 hover:text-[#07A4A2] transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <i className="fas fa-info-circle" /> من نحن
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/support" onClick={toggleSidebar} className="flex items-center gap-3 p-4 text-[#0A3A6B] font-bold rounded-xl hover:bg-gray-100 hover:text-[#07A4A2] transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <i className="fas fa-headset" /> الدعم الفني
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </aside>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div ref={spacerRef} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div ref={stickyRef} className={`fixed top-0 left-0 w-full z-[1000] bg-white transition-transform duration-300 ${hideHeader ? "-translate-y-full" : "translate-y-0"}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="py-4 border-b border-gray-100 bg-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="max-w-[1200px] mx-auto px-5 flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/" className="hidden max-md:block ml-4 shrink-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img src="http://a.theorix.net/wp-content/uploads/2026/04/file_0000000083d4720abfa704bf8b172784.png" alt="شعار" className="h-[35px] md:h-[42px] w-auto object-contain" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative flex-1 flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <i className="fas fa-search absolute right-5 text-[#07A4A2] text-lg" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="text" placeholder="ابحث عن دورة..." className="w-full border-none rounded-[50px] bg-gray-100 py-3 pr-[55px] pl-[110px] text-sm outline-none" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="absolute left-1.5 bg-[#0A3A6B] text-white border-none py-2 px-6 rounded-[50px] font-bold cursor-pointer">استكشف</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <header className="py-2.5 bg-white border-b border-gray-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="max-w-[1200px] mx-auto px-5 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div onClick={toggleSidebar} className="w-[42px] h-[42px] bg-gray-100 rounded-xl flex items-center justify-center cursor-pointer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="block w-5 h-0.5 bg-[#0A3A6B] my-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="block w-5 h-0.5 bg-[#0A3A6B] my-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="block w-5 h-0.5 bg-[#0A3A6B] my-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/" className="max-md:hidden flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <img src="http://a.theorix.net/wp-content/uploads/2026/04/file_0000000083d4720abfa704bf8b172784.png" alt="شعار" className="h-[42px] w-auto max-w-[150px] object-contain" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-gray-100 p-1 rounded-[50px] w-[320px] max-[500px]:w-[110px] h-12 relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex justify-between h-full relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className={`absolute top-0 h-full w-1/2 bg-gradient-to-l from-[#0A3A6B] to-[#07A4A2] rounded-[50px] transition-all duration-400 z-10 ${mode === "student" ? "right-0" : "right-1/2"}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/" className={`w-1/2 flex items-center justify-center gap-2 font-bold text-sm z-20 no-underline ${mode === "student" ? "text-white" : "text-gray-500"}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <i className="fas fa-user-graduate" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="max-[500px]:hidden">منصة الطالب</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link href="/upload-course" className={`w-1/2 flex items-center justify-center gap-2 font-bold text-sm z-20 no-underline ${mode === "teacher" ? "text-white" : "text-gray-500"}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <i className="fas fa-chalkboard-teacher" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="max-[500px]:hidden">لوحة المعلم</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/login" className="text-[27px] text-[#0A3A6B] no-underline flex">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i className="fas fa-user-circle" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/cart" className="text-2xl text-[#0A3A6B] no-underline relative flex">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i className="fas fa-shopping-cart" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="absolute -top-1 -left-2 bg-[#07A4A2] text-white text-[10px] px-1.5 py-0.5 rounded-[50px] border-2 border-white">0</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }