'use client';

import { useState } from 'react';
import { useCartStore } from '@/lib/cart-store';

const popularCourses = [
  { id: 1, title: "دورة تطوير المواقع الشاملة", category: "برمجة", price: 299, image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=600" },
    { id: 2, title: "أساسيات الذكاء الاصطناعي", category: "تقنية", price: 199, image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=600" },
      { id: 3, title: "التسويق الرقمي المتقدم", category: "أعمال", price: 349, image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600" },
        { id: 4, title: "تحليل البيانات الضخمة", category: "تقنية", price: 449, image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600" },
          { id: 5, title: "الإدارة المالية المتقدمة", category: "أعمال", price: 259, image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600" },
          ];

          const allCourses = [
            { id: 6, title: "تعلم اللغة الإنجليزية للأعمال", category: "لغات", price: 249, image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=600" },
              { id: 7, title: "إدارة المشاريع الاحترافية PMP", category: "إدارة", price: 399, image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600" },
                { id: 8, title: "تصميم تجربة المستخدم UI/UX", category: "تصميم", price: 279, image: "https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=600" },
                  { id: 9, title: "أمن المعلومات والشبكات", category: "تقنية", price: 599, image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600" },
                    { id: 10, title: "صناعة المحتوى الرقمي", category: "إعلام", price: 199, image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=600" },
                      { id: 11, title: "مهارات البيع والتفاوض", category: "أعمال", price: 329, image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600" },
                        { id: 12, title: "برمجة تطبيقات iOS", category: "برمجة", price: 499, image: "https://images.unsplash.com/photo-1621839673705-6617adf9e890?auto=format&fit=crop&w=600" },
                          { id: 13, title: "التصوير الفوتوغرافي", category: "فنون", price: 179, image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600" },
                          ];

                          export default function HomePage() {
                            const addItem = useCartStore((state) => state.addItem);

                              function goToCourse(id: number) {
                                  window.location.href = '/course/' + id;
                                    }

                                      return (
                                          <main className="w-full max-w-[1200px] mx-auto px-5 pb-16">
                                                <div className="mt-5 mb-8 rounded-[25px] overflow-hidden h-[160px] md:h-[250px] shadow-md border border-gray-200">
                                                        <img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200" alt="بانر" className="w-full h-full object-cover" />
                                                              </div>
                                                                    <div className="flex items-center gap-3 my-[35px]">
                                                                            <h2 className="text-xl md:text-2xl font-black bg-gradient-to-l from-[#0A3A6B] to-[#07A4A2] bg-clip-text text-transparent whitespace-nowrap">الأكثر مبيعاً 🔥</h2>
                                                                                    <div className="flex-1 h-[2px] bg-gray-200" />
                                                                                          </div>
                                                                                                <div className="flex overflow-x-auto gap-4 pb-8 snap-x snap-mandatory scrollbar-none">
                                                                                                        {popularCourses.map((c) => (
                                                                                                                  <Card key={c.id} {...c} onAdd={addItem} onGoToCourse={goToCourse} />
                                                                                                                          ))}
                                                                                                                                </div>
                                                                                                                                      <div className="flex items-center gap-3 my-[35px]">
                                                                                                                                              <h2 className="text-xl md:text-2xl font-black bg-gradient-to-l from-[#0A3A6B] to-[#07A4A2] bg-clip-text text-transparent whitespace-nowrap">جميع الدورات ✨</h2>
                                                                                                                                                      <div className="flex-1 h-[2px] bg-gray-200" />
                                                                                                                                                            </div>
                                                                                                                                                                  <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-[12px] md:gap-[20px]">
                                                                                                                                                                          {allCourses.map((c) => (
                                                                                                                                                                                    <Card key={c.id} {...c} onAdd={addItem} onGoToCourse={goToCourse} />
                                                                                                                                                                                            ))}
                                                                                                                                                                                                  </div>
                                                                                                                                                                                                      </main>
                                                                                                                                                                                                        );
                                                                                                                                                                                                        }

                                                                                                                                                                                                        function Card({
                                                                                                                                                                                                          id,
                                                                                                                                                                                                            title,
                                                                                                                                                                                                              category,
                                                                                                                                                                                                                price,
                                                                                                                                                                                                                  image,
                                                                                                                                                                                                                    onAdd,
                                                                                                                                                                                                                      onGoToCourse,
                                                                                                                                                                                                                      }: {
                                                                                                                                                                                                                        id: number;
                                                                                                                                                                                                                          title: string;
                                                                                                                                                                                                                            category: string;
                                                                                                                                                                                                                              price: number;
                                                                                                                                                                                                                                image: string;
                                                                                                                                                                                                                                  onAdd: (id: number, title: string, price: number) => void;
                                                                                                                                                                                                                                    onGoToCourse: (id: number) => void;
                                                                                                                                                                                                                                    }) {
                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                          <div className="bg-white rounded-[22px] md:rounded-[28px] border border-gray-200 shadow-sm hover:-translate-y-1 hover:shadow-lg hover:border-[#07A4A2] transition-all duration-300 min-w-[210px] snap-start flex flex-col">
                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                        src={image}
                                                                                                                                                                                                                                                                alt={title}
                                                                                                                                                                                                                                                                        className="w-full h-[115px] md:h-[160px] object-cover rounded-t-[22px] md:rounded-t-[28px] cursor-pointer"
                                                                                                                                                                                                                                                                                onClick={() => onGoToCourse(id)}
                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                            <div className="p-3 md:p-[18px] flex flex-col items-center text-center flex-1">
                                                                                                                                                                                                                                                                                                    <span className="bg-blue-50 text-black px-3 py-1 rounded-[10px] text-[9px] md:text-[10px] font-extrabold mb-2 md:mb-3">{category}</span>
                                                                                                                                                                                                                                                                                                            <h3
                                                                                                                                                                                                                                                                                                                      className="font-extrabold text-xs md:text-[15px] text-[#0A3A6B] mb-3 md:mb-[15px] leading-relaxed min-h-[34px] md:min-h-[44px] cursor-pointer hover:text-[#07A4A2] transition-colors"
                                                                                                                                                                                                                                                                                                                                onClick={() => onGoToCourse(id)}
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                  {title}
                                                                                                                                                                                                                                                                                                                                                          </h3>
                                                                                                                                                                                                                                                                                                                                                                  <p className="font-black text-lg md:text-2xl text-[#0A3A6B] mb-3 md:mb-[20px]"><span className="text-[10px] md:text-xs text-gray-400 mr-1">ريال</span>{price}</p>
                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                    className="w-full py-[10px] md:py-[14px] bg-[#10b981] hover:bg-[#0ea171] text-white font-extrabold text-[11px] md:text-sm rounded-[12px] md:rounded-[15px] transition-all duration-300 hover:scale-[1.02] hover:shadow-lg cursor-pointer border-none"
                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => onAdd(id, title, price)}
                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                أضف للسلة
                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                    }