import Link from "next/link";

export default function UploadCoursePage() {
  return (
      <div className="font-[Cairo] bg-[#fdfdfe] min-h-screen py-10 px-4" dir="rtl">
            <div className="max-w-[1100px] mx-auto">
                    <div className="text-center mb-8">
                              <h1 className="text-[#0A3A6B] text-[28px] font-black">مرحباً، <span className="text-[#07A4A2]">أستاذ أحمد</span></h1>
                                      </div>
                                              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                                                        <div className="bg-white rounded-[25px] border-2 border-dashed border-gray-300 hover:border-[#07A4A2] hover:-translate-y-2.5 hover:shadow-xl transition-all">
                                                                    <Link href="/upload-course/new" className="h-full flex flex-col items-center justify-center no-underline py-[50px]">
                                                                                  <div className="relative w-20 h-20 flex items-center justify-center mb-5">
                                                                                                  <div className="absolute w-full h-full bg-[#07A4A2] opacity-15 rounded-full" />
                                                                                                                  <i className="fas fa-plus text-[45px] text-[#07A4A2] relative" />
                                                                                                                                </div>
                                                                                                                                              <span className="text-[#0A3A6B] text-lg font-extrabold">أضف دورة جديدة</span>
                                                                                                                                                          </Link>
                                                                                                                                                                    </div>
                                                                                                                                                                              {[1,2,3].map((i) => (
                                                                                                                                                                                          <div key={i} className="bg-white rounded-[25px] border border-gray-200 overflow-hidden hover:-translate-y-2.5 hover:shadow-xl hover:border-[#07A4A2] transition-all">
                                                                                                                                                                                                        <div className="relative h-[160px]">
                                                                                                                                                                                                                        <img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=600" className="w-full h-full object-cover" alt="دورة" />
                                                                                                                                                                                                                                        <div className="absolute top-3 left-3 bg-white rounded-xl py-1.5 px-3.5 flex items-center gap-2.5 shadow-md">
                                                                                                                                                                                                                                                          <i className="fas fa-coins text-[#07A4A2] text-lg" />
                                                                                                                                                                                                                                                                            <div className="flex flex-col"><small className="text-[9px] text-gray-500 font-bold">الأرباح</small><strong className="text-[13px] text-[#0A3A6B] font-black">12,450 ريال</strong></div>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                            <span className="absolute top-3 right-3 bg-[#10b981] text-[10px] py-1 px-3 rounded-[50px] text-white font-extrabold">نشطة</span>
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                        <div className="p-5">
                                                                                                                                                                                                                                                                                                                                                        <div className="flex justify-between items-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                          <span className="bg-gray-100 text-[#0A3A6B] py-1.5 px-3 rounded-lg text-[11px] font-extrabold flex items-center gap-1.5"><i className="fas fa-code" /> برمجة</span>
                                                                                                                                                                                                                                                                                                                                                                                            <span className="bg-red-50 text-red-500 py-1.5 px-3 rounded-lg text-[11px] font-extrabold flex items-center gap-1.5"><i className="fas fa-chair" /> 34 مقعد</span>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-[#0A3A6B] text-base font-extrabold mb-3 h-[45px] overflow-hidden leading-relaxed">دورة تطوير المواقع الشاملة</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2 text-[#64748b] text-[13px] font-bold mb-5"><i className="fas fa-users text-[#07A4A2]" /><span>89 طالب مسجل</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-col gap-2.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/manage-course/1" className="text-center no-underline py-3 rounded-2xl text-sm font-extrabold flex items-center justify-center gap-2 bg-[#0A3A6B] text-white hover:bg-[#07A4A2] transition"><i className="fas fa-chart-line" /> إدارة الدورة</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="py-3 rounded-2xl text-sm font-extrabold flex items-center justify-center gap-2 bg-white text-[#0A3A6B] border-2 border-gray-200 hover:border-[#07A4A2] hover:text-[#07A4A2] hover:bg-teal-50 transition cursor-pointer"><i className="fas fa-qrcode" /> استخراج أكواد</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }